### ISSUE TITLE
No details shown

### ISSUE THREAD

**Issue by sharkxii** [analytics-debugger/analytics-debugger-browser-extension#10]
**Describe the bug**
Hit details bot shown

**To Reproduce**
1.  All pages
2. GA3/GA4
3. All pages

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem. 
![8B753478-88A9-461D-99D8-8AB236B9A623](https://user-images.githubusercontent.com/39593838/197208630-571308a9-9732-498b-982c-e7988f4470e8.jpeg)
![DFE4EAC2-6F96-448E-ADB6-D6E8F10642DC](https://user-images.githubusercontent.com/39593838/197208642-c99846e7-51b8-45f8-a7a4-f6a5a2946eb3.jpeg)

**Environment (please complete the following information):**
 - Version [e.g. 105.xx.xxx]

**Additional context**

**Comment by thyngster** [comment]
Not sure if I get the issue, It works fine on my end: 
![image](https://user-images.githubusercontent.com/1494564/197221275-a969f30a-101e-4acc-90b8-0281ea521ea6.png)

Looks like the current report is collapsed anyway, if you click on the URL does it expand and show the data?

**Comment by sharkxii** [comment]
Hi. No, nothing expands. 
I also tried removing, Rebooting then re-adding. Played with options but nothing changed.

**Comment by thyngster** [comment]
@sharkxii I'm not able to replicate this, does it happens with any other sites?,  would you mind jumping into a quick call to do a screenshare ?

**Comment by thyngster** [comment]
HI , I think I have finally found the issue. Next will will have a fix. @sharkxii

**Comment by thyngster** [comment]
This should be addresed on the last 2.3.0 version, Thanks
