### ISSUE TITLE
Debug dialog in corner on page I'm not debugging

### ISSUE THREAD

**Issue by nikjft** [analytics-debugger/analytics-debugger-browser-extension#11]
**Describe the bug**
Getting a little debugging window in the corner even when I'm not in debug mode

**To Reproduce**
1. Go to trello.com
2. It shows up (see screenshot)

I do not have debug enhancer open or anything like that.

**Expected behavior**
Not to see that

**Screenshots**
See attachment

**Environment (please complete the following information):**
Chrome, latest version

**Additional context**

![image](https://user-images.githubusercontent.com/828123/197249162-cfd6b80b-8cc9-4301-90ce-b0b05b63cfe8.png)

**Comment by thyngster** [comment]
Hi @nikjft this has been identified, it happens when you the site uses the gtm environments (which is kinda a preview internally). flagging this a bug

**Comment by thyngster** [comment]
This has been fixed. Shipping with the next release.

**Comment by thyngster** [comment]
@nikjft this shipped with 2.0.2 version. Now this won't show up if on environments or if the current preview mode was not set from the tool
