### ISSUE TITLE
Cannot copy text from GA hit details 

### ISSUE THREAD

**Issue by tianzhang0611** [analytics-debugger/analytics-debugger-browser-extension#12]
**Describe the bug**
It is not able to copy text from the hit payload details.

**To Reproduce**
1. Does it happens in all pages? Yes
2. Which vendors is giving problems ( GA4, Matomo, Amplitude, Others specify ) GA3
3. Share the site / url your're debugging ( if you don't want to share the link publicly, please keep filling the issue and share it via an email  www.porsche.com/germany

**Expected behavior**
A single line of text in the hit payload detail can be selected and copied.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Environment (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 105.xx.xxx]  Version 106.0.5249.119 (Official Build) (x86_64)

**Additional context**

**Comment by thyngster** [comment]
Sorry it's not the same. It's not possible to select any text, you need to export the details.
