### ISSUE TITLE
Pressing "Start debugging" does not work

### ISSUE THREAD

**Issue by MajaMathem** [analytics-debugger/analytics-debugger-browser-extension#16]
**Describe the bug**
Pressing start debugging does not start the debugging. So it cannot be used.

**To Reproduce**
1. Does it happens in all pages? : Yes.
2. Which vendors is giving problems ( GA4, Matomo, Amplitude, Others specify ): All I guess
3. Share the site / url your're debugging ( if you don't want to share the link publicly, please keep filling the issue and share it via an email : www.mathem.se

**Expected behavior**
I expect that i can start debugging when pressing "Start debugg", it does not take me to any other view it just stays at the start debugging view. 

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Environment (please complete the following information):**
 - Browser [e.g. chrome, safari]: chrome 
 - Version [e.g. 105.xx.xxx] : Version 105.0.5195.125

**Comment by thyngster** [comment]
HI , I think I have finally found the issue. Next will will have a fix. @MajaMathem

**Comment by twerthmueller** [comment]
Expected the same behaviour, start debugging does reload the page but not really start the debugging. Not sure is this related to a Google Chrome update, but 1 or 2 weeks ago it worked as expected.

**Comment by rich13579** [comment]
Hi, I am also having the same problem - my first time using the extension since the update.

**Comment by thyngster** [comment]
a bit late but a new improved version is now live. tested the site and worked fine at my end.
