### ISSUE TITLE
Bundled GA4 parameters not reflected correctly

### ISSUE THREAD

**Issue by loldenburg** [analytics-debugger/analytics-debugger-browser-extension#18]
**Describe the bug**
If I cause Events with different document title and document location parameters quickly, e.g., by navigating quickly through a Single-Page App, GA4 bundles these events  as usual. However, the Analytics Debugger shows the **first** value for all bundled Events and not the actual value. It can be verified with Fiddler and GA4 debug mode that the data sent was correct, but Analytics Debugger did not show it correctly. 

**To Reproduce**
Navigate quickly on a Single Page App to send different individual page_view Events with different page_title and page_location parameters (dl and dt). You will see that bundled events have one and the same value for all bundled page_view events.

I have sent a video to David Vallejo via Twitter which I cannot post here due to it containing PII and client information. Please treat it privately.

1. Does it happens in all pages?
Yes

2. Which vendors is giving problems ( GA4, Matomo, Amplitude, Others specify )
GA4

4. Share the site / url your're debugging ( if you don't want to share the link publicly, please keep filling the issue and share it via an email 
shared via email

**Expected behavior**
=> the values in the debugger must reflect the actual values sent to GA4

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.
=> See video shared

**Environment (please complete the following information):**
 - Version [e.g. 105.xx.xxx]
=> Chrome and Opera, newest versions

**Additional context**
=> should be all clear?

**Comment by thyngster** [comment]
Hi, I'm aware of this and it's currently fixed on the upcoming 2.2.0 release...

**Comment by thyngster** [comment]
This should be addresed on the last 2.3.0 version, Thanks
