### ISSUE TITLE
No detection of GA4 Ecommerce

### ISSUE THREAD

**Issue by PALConverteo** [analytics-debugger/analytics-debugger-browser-extension#19]
**Describe the bug**
The format of the products array send to GA4 is not read correctly by the extension

**To Reproduce**
1. Does it happens in all pages? Yes, but we focus on ecommerce product page with view_item hits
2. Which vendors is giving problems ( GA4, Matomo, Amplitude, Others specify ) GA4
3. Share the site / url your're debugging ( if you don't want to share the link publicly, please keep filling the issue and share it via an email  https://www.conforama.fr/gros-electromenager/refrigerateur/tous-les-refrigerateurs/refrigerateur-multiportes-saba-frd5021wdil/p/741346

**Expected behavior**

Ecommerce fields should be set in the debugger

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.
![image](https://user-images.githubusercontent.com/57902745/206220452-ded306fb-265a-44c4-ab76-2cadf6eaa5c2.png)

**Environment (please complete the following information):**
 - Version [e.g. 105.xx.xxx]

Chrome Version 107.0.5304.122 (Build officiel) (64 bits)

**Comment by thyngster** [comment]
Hi, this is already fixed on the dev branc since 3 weeks ago. will be shipped on next release.

**Comment by JFAmprimoz** [comment]
Has this release launched yet or is it held up in chrome extension approval land?

**Comment by thyngster** [comment]
This should be addresed on the last 2.3.0 version, Thanks
