### ISSUE TITLE
GTM Preview Modal impacts UX

### ISSUE THREAD

**Issue by moonpigalex** [analytics-debugger/analytics-debugger-browser-extension#2]
**Describe the bug**
The GTM Preview overlay obstructs parts of site UX being the size it is and position in the bottom right-hand corner.

**To Reproduce**
1. Open site page in GTM preview mode
2. GTM 

**Expected behaviour**
Option to dismiss or move the overlay potentially

**Screenshots**
See a 'Preview' button where the window has been manually resized to make the button visible and clickable
![preview-button-obscured](https://user-images.githubusercontent.com/63397522/196936283-9b0872e4-5c0a-48c4-aae0-5ff2f04b9d06.png)

**Environment (please complete the following information):**
 - Chrome
 - 106.0.5249.119 (Official Build) (64-bit)

**Comment by thyngster** [comment]
hmm, there shoud been a close button. Flagging this as a bug. It will fixed on the next update.

**Comment by thyngster** [comment]
This has been fixed on the dev branch, now you can dismiss the notification. Will be shipped on the next update.

**Comment by thyngster** [comment]
@moonpigalex this has been fix on the version 2.0.2 . You'll now be able to close the toast, or it will dissapear automatically after 7.5 seconds
