### ISSUE TITLE
It's a pain to find the extension because of inconstent naming

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [analytics-debugger/analytics-debugger-browser-extension#21]
**Describe the bug**
In the list of installed extensions, it's named "GTM/GA Debugger", as on https://www.thyngster.com/tools
The Console pane is titled "Analytics Debugger" like on https://www.thyngster.com/analytics-debugger-2-0-0-chrome-extension-release 

The extension made by Google is named "Google Analytics Debugger"

It's confusing ... A single name should be used everywhere, as far as possible

Thanks David for your work and attention

**Comment by thyngster** [comment]
calling this a pain is bit bit I think . Name migrations have a timing and way for doing things rather than "just" changing a name. Thanks for your report.
