### ISSUE TITLE
Keep the panel expanded across pages in SPA navigation

### ISSUE THREAD

**Issue by krisknap** [analytics-debugger/analytics-debugger-browser-extension#22]
**Describe the bug**
The prior major version kept the events in the open panel across gtm.historyChange events, but the current version closes it when the URL change occurs. Would it be possible to keep it open?

**To Reproduce**
1. Does it happen in all pages? this pertains to pages that change the URL but are not fully reloaded
2. Which vendors is giving problems GTM, GA3, GA4 panels/tabs
3. Share the site / url your're debugging ( if you don't want to share the link publicly, please keep filling the issue and share it via an email **will share via email**

**Expected behavior**
Keep the panel open, as the new URL and other events accummulate. Saves time/clicks and retains focus

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Environment (please complete the following information):**
 - Browser Chrome
 - Version 108 but this is not a browser issue imo

**Additional context**
Thank you Dave for all your efforts - greatly appreciated. This extension is used by many in our org!

**Comment by thyngster** [comment]
This should be improved on the last 2.3.0 version, Thanks

**Comment by TwisterMc** [comment]
I have this issue with the current version 2.4.6. I'd love it if the extension retained my focus state and didn't close the current accordion or scroll me away from what I'm looking at. Not a deal breaker, but it'd be nice.
