### ISSUE TITLE
Issues when running GTM through Partytown

### ISSUE THREAD

**Issue by fabregas4** [analytics-debugger/analytics-debugger-browser-extension#25]
Partytown is a script that reduces the performance impacts of 3rd party scripts like Google Tag Manager by moving it off the main thread. It's still technically in Beta but it is widely known and used.

https://partytown.builder.io/

When using Analytics Debugger while using Partytown. the "GTM/GTAG" Pushes List doesn't appear/load. I'm just getting the spinner forever. The DataLayer Message and Model show "Object - No properties". 

However, I'm pretty sure it is working, because the GA4 tab is showing my ecommerce events like 'view_item', 'begin_checkout', etc.

Should the GTM/GTAG tab load data when Partytown is being used? If not, would you be able to add support for it?

**Comment by thyngster** [comment]
GTM is injected from a webworker and it's executed on a private context. that's why the extensoin is not able to report about it. It still detects a GTM container hit and GA hits. But won't be able to read the dataLayer or anything while being on a private context. 

Won't fix.
