### ISSUE TITLE
Debugger fails to initialise

### ISSUE THREAD

**Issue by leohennessy** [analytics-debugger/analytics-debugger-browser-extension#26]
When opening the debugger via dev tools, and hitting 'start debugging', the page reloads but nothing changes in the debug console, and any pushes do not display

Same behaviour on all pages
Issue affecting GA4 
Occuring on www.listnr.com

Chrome Version 110.0.5481.178 (Official Build) (64-bit)

**Comment by thyngster** [comment]
Please try the last 2.3.0 version released today.
