### ISSUE TITLE
Google Signals status, Consent Mode, isConversion don't seem accurate when using region1.google-analytics.com

### ISSUE THREAD

**Issue by googleanalyticsresoneo** [analytics-debugger/analytics-debugger-browser-extension#29]
Multiple diagnostics about a hit don't seem accurate when the hit occurs in Europe and is targeted to region1.google-analytics.com

**To Reproduce**
1. Does it happens in all pages? Yes
2. Which vendors is giving problems : GA4
3. Share the site / url your're debugging : https://converteo.com/media/dashboarding-et-attribution/ 
4. Use a VPN to connect from Europe

**Expected behavior**
- Google Signals is disabled on this site, when enabled hits would go to region1.analytics.google.com
- this is not Server Side
- Consent Mode gcs=G111 is present but displayed as n/a
- this is just a page_view, not a conversion

**Screenshots**
![2023-03-26 13_30_02-Dashboarding et attribution - Converteo bug report](https://user-images.githubusercontent.com/282461/227773418-130ada28-32cb-40b3-8269-cc0cf7ea0ece.png)

**Environment (please complete the following information):**
 - Chrome Version 111.0.5563.111 / Window 10

**Additional context**
IP address in France

**Comment by thyngster** [comment]
A cross-mark ❎ usually doesn't mean OK. so there measnt hat is NOT server side, that is NOT a converison and that Signal was NOT enabled on that hit. You'll see ✅ instead if that condition was true.

About the consent mode was fixed on the last release

**Comment by googleanalyticsresoneo** [comment]
well, a green cross-mark could look as a green check-mark... 
since we can't get guess what will display for the opposite value, it would be nice to have something more explicit (empty ? red cross-mark...)

**Comment by thyngster** [comment]
Thank you for sharing your perspective. In my view, the cross-mark (❎) and the check-mark (✅) hold totally distinct and  identificaly meanings that are not solely based on their color.

**Comment by googleanalyticsresoneo** [comment]
Hi,

I still believe that using a different color would help grasping the status at a glance instead of requiring precise decoding 
Grey for example

**Comment by thyngster** [comment]
Again it's how Chrome shows these unicode icons. I won't change it. The
icon itself it's self explanatory.
