### ISSUE TITLE
GA4 event fall under custome in Data Layer Filters

### ISSUE THREAD

**Issue by ZeBeard** [analytics-debugger/analytics-debugger-browser-extension#4]
In the previous version, the GA4 event was under the GA4 Events filter in Data Layer Filters now they fall into the Custom filter
For example 
begin_checkout event in GTM/GA debugger was in the GA4 Events filter, in the new Analytics it is now in the custom
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/72789347/197000642-1f847c94-2fa8-4fb2-a00f-4e781b9f1ce0.png">
Now GA4 Events filter is always empty
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/72789347/197001626-3de73d2e-0942-4ff0-a242-9a10216721bb.png">

**Comment by thyngster** [comment]
@ZeBeard for some reason the build is missing the predefined events list, that's why it's failing under the custom category. Will be fixed in next. Release, Thanks you for the report.

**Comment by thyngster** [comment]
This has been fixed on the local branch. The fix will be shipped with the next release.

**Comment by thyngster** [comment]
@ZeBeard this has been fixed on version 2.0.2 .
