### ISSUE TITLE
EEC Data stays empty

### ISSUE THREAD

**Issue by melvinio** [analytics-debugger/analytics-debugger-browser-extension#6]
With the previous versions I had proper EEC data within the debugger, however the data stays 'greyed out' on all my stores while the data still seems to be sent.

Would it be possible to take a look at?

![image](https://user-images.githubusercontent.com/47391083/197139772-bb15f180-cefd-4701-b52f-493954c68657.png)

Thanks in advance!

**Comment by thyngster** [comment]
Since GA4 Ecommerce Data is based on events, I removed it from this report (you can check the data in the event itself ). I may bring it back., let me give it a spin.

**Comment by melvinio** [comment]
hi @thyngster , thanks for your quick reply. 
the EEC overview gives a clear overview if the ecommerce data is correctly (besides the event-data for example). and of course GA3 is still active untill July next year :) 

Thanks!

**Comment by thyngster** [comment]
GA3, should show  the details. In any I'm giving all these a revamp for the next version.

**Comment by yoraysa** [comment]
testing @ the end of 2022:


_*refreshing the same page each time using the gtm preview mode button_
first 2 pages EEC tab **worked**
3rd+ pages the EEC tab is **disabled
![2022-12-22_9-15-40](https://user-images.githubusercontent.com/9439146/209078956-d7104bfe-bf59-4624-96bf-937874c233a2.png)
**

GA4 tab has an ecommerce items section but unfortunately it shows "No Data"
GA4 tab raw payload details is quite messy for EE, hard to read the raw event array.


It's not that there is a bug or something, looking at the network tab, the hit seems to work.

**Comment by thyngster** [comment]
Finally fixed.
