### ISSUE TITLE
Copying the payload is not working after the update to Analytics Debugger

### ISSUE THREAD

**Issue by extdivya** [analytics-debugger/analytics-debugger-browser-extension#7]
After updating the ext to Analytics Debugger, we're not able to copy the payload code

**To Reproduce**
1. Does it happens in all pages? - Yes
2. Which vendors is giving problems ( GA4, Matomo, Amplitude, Others specify ) - All

**Expected behavior**
We are expecting the code to be copied properly for the purpose of debugging and report it to the concerned person in the organziation 

**Environment (Brave, Chrome):**

**Comment by thyngster** [comment]
Hi, I'm trying to replicate this, and it's working for me on Chrome and Brave. Sometimes the extension may have some internal problema that blocks the right behaviour until it get restarsted. Can you restart your browser and try again?

**Comment by thyngster** [comment]
@extdivya this has been addresed on version 2.0.2
