### ISSUE TITLE
Extension doesn't load

### ISSUE THREAD

**Issue by d3xtr0** [analytics-debugger/analytics-debugger-browser-extension#8]
**Describe the bug**
The Tab "Analytics Debugger" is missing after the update to 2.0.0. Clicking the extension icon again shows the tab, but only with a white screen:
![image](https://user-images.githubusercontent.com/18446160/197169149-366afc7b-dae8-447a-bf59-c84886447cde.png)

Clicking the extension again loads the extension, but clicking "Start debugging" only reloads the page and keeps displaying "Start debugging".

Clicking the extension about 5-8 times again finally shows the debug screen, but when navigating to another page it is stuck on the old page.

**To Reproduce**
1. Does it happens in all pages? Yes

Works fine in Incognio mode.
Tried uninstalling and reinstalling.

**Environment (please complete the following information):**
 - Version 106.0.5249.119 (Official Build) (64-Bit)
 - Disabled any other extension

**Additional context**
On another computer installing it fresh (without previous installation) works fine

**Comment by thyngster** [comment]
can't replicate this. do you mind remove and reinstaling the extension and letting me know if it made a difference ?

**Comment by thyngster** [comment]
Seeing that you opened another ticket sohwing some report I'm closing this ticket.
