### ISSUE TITLE
Missing GA4 ecommerce items

### ISSUE THREAD

**Issue by d3xtr0** [analytics-debugger/analytics-debugger-browser-extension#9]
**Describe the bug**
view_item_list (and sometimes view_item) doesn't show sent ecommerce items.

**To Reproduce**
1. Does it happens in all pages? Any products list / details page
2. Which vendors is giving problems? GA4

**Expected behavior**
Should show a list of sent ecommerce items 

**Screenshots**
![image](https://user-images.githubusercontent.com/18446160/197174737-970f64e2-51c2-44fc-bba0-9793f0bfb055.png)
![image](https://user-images.githubusercontent.com/18446160/197175347-edef6301-b3ab-42f1-bfe1-4bc859e77af2.png)
![image](https://user-images.githubusercontent.com/18446160/197177739-d71ae471-0f19-412d-87fd-0018b50bc596.png)

**Environment (please complete the following information):**
 - Version 106.0.5249.119 (Official Build) (64-Bit)

**Additional context**
Tag setup was done via GTM:
![image](https://user-images.githubusercontent.com/18446160/197176743-ce80a320-f106-4754-9fcb-7247193f020a.png)

**Comment by thyngster** [comment]
Hi, again I cannot replicate this, it shows me info on the sites I'm testing, If you could share the URL you're testing I could try it at my end. ( feel free to email me if you don't want to expose the details here.)

**Comment by thyngster** [comment]
Fix shipping on upcoming version 2.1.0

**Comment by thyngster** [comment]
@d3xtr0 this should had been fixed, would you mind confirming it?

**Comment by thyngster** [comment]
This should be addresed on the last 2.3.0 version, Thanks
